export let products = [
  {
    id: 1,
    title: "Raza",
    price: 2400,
    description: "Alimento para perros 6kg",
    img: "https://res.cloudinary.com/dxyonwc26/image/upload/v1711679707/RAZA_mgueme.png",
    stock: 14,
    category: "Perros",
  },
  {
    id: 2,
    title: "Eukanuba",
    price: 3000,
    description: "Alimento para perros 3kg",
    img: "https://res.cloudinary.com/dxyonwc26/image/upload/v1711680767/EUKANUBA_m0cjwe.png",
    stock: 20,
    category: "Perros",
  },
  {
    id: 3,
    title: "Excellent",
    price: 2400,
    description: "Alimento para perros 8kg",
    img: "https://res.cloudinary.com/dxyonwc26/image/upload/v1711680888/EXCELENT_b9jyrx.png",
    stock: 10,
    category: "Perros",
  },
  {
    id: 4,
    title: "Whiskas",
    price: 1500,
    description: "Alimento para gatos 2kg",
    img: "https://www.whiskas.com.ar/cdn-cgi/image/format=auto,q=90/sites/g/files/fnmzdf4921/files/2022-12/7797453972338-product-image-1.png",
    stock: 18,
    category: "Gatos",
  },
  {
    id: 5,
    title: "Cat chow",
    price: 2000,
    description: "Alimento para gatos 3kg",
    img: "https://www.purina.com.ar/sites/default/files/2023-04/ADULTOS%20CARNE%20Y%20POLLO-cat-chow-frente.png",
    stock: 15,
    category: "Gatos",
  },
  {
    id: 6,
    title: "Gati",
    price: 1700,
    description: "Alimento para gatos 5kg",
    img: "https://www.purina.com.ar/sites/default/files/styles/simple_card/public/2023-01/gati_pescado_salmon_a_la_primavera.png.webp?itok=XxG_mlOM",
    stock: 12,
    category: "Gatos",
  },
];